spring:
 application:
   name: HelloServices
server:
     port: 0
#     dynamic port no
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
         defaultZone: http://localhost:8761/eureka   
#         server should run on 8761
  instance: 
    hostname: localhost    


